# -*- coding: utf-8 -*-
"""Function5_Tweets/day.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DGYl1YQ_3vU0ymXNTvJ-oZ0hbz9hkpFX
"""
import pandas as pd
### START FUNCTION
def number_of_tweets_per_day(df):

  mod_date = [i.split(' ', 1)[0] for i in dates]
  twitter_df = pd.read_csv(twitter_url)
  twitter_df_by_tweets= twitter_df.groupby(mod_date)['Tweets'].count()
  new_dataframe = pd.DataFrame(twitter_df_by_tweets).rename_axis('Date')
  return new_dataframe
number_of_tweets_per_day(twitter_df.copy())

### END FUNCTION