# -*- coding: utf-8 -*-
"""Function 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lRhvcUZ_U83-VY9SppU5u2EGJ5hb1JNl
"""

### START FUNCTION
def extract_municipality_hashtags(df):
    # your code here
    municipality_dict = { '@CityofCTAlerts' : 'Cape Town',
            '@CityPowerJhb' : 'Johannesburg',
            '@eThekwiniM' : 'eThekwini' ,
            '@EMMInfo' : 'Ekurhuleni',
            '@centlecutility' : 'Mangaung',
            '@NMBmunicipality' : 'Nelson Mandela Bay',
            '@CityTshwane' : 'Tshwane'}
     
    list_with_hashtags = []
    final_list_with_hashtags = []
    
    list_with_mun = []
    final_list_with_mun = []
    
    
    
    for tweet in df['Tweets']:
        if '#' in tweet:
            list_with_hashtags.append(tweet.lower())

        else:
            list_with_hashtags.append(np.nan)      

    list_of_list_with_hashtags = [i.split() if i is not np.nan else i for i in list_with_hashtags]
    
    for value in list_of_list_with_hashtags:
        if value is not np.nan:
            final_list_with_hashtags.append([value2 for value2 in value if value2[0] == '#'])
        else:
            final_list_with_hashtags.append(value)


    for tweets in df['Tweets']:
        if '@' in tweets:
            list_with_mun.append(tweets)
        else:
            list_with_mun.append(str(np.nan))
            
    rows = [i.split() if i is not str(np.nan) else i for i in list_with_mun]
    
    list_of_keys = []
    
    for key in municipality_dict.keys():
        list_of_keys.append(key)

    for list_value in rows:
        for value in list_value:
            if value in list_of_keys:
                final_list_with_mun.append(municipality_dict[value])
            else:
                final_list_with_mun.append(str(np.nan))

### END FUNCTION