# -*- coding: utf-8 -*-
"""Function3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ShJsf7zr_8baYk8YHu0RfRtgx7HNbJhN
"""

### START FUNCTION
dates = twitter_df['Date'].to_list()
twitter_url = 'https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/twitter_nov_2019.csv'
twitter_df = pd.read_csv(twitter_url)

def date_parser(dates):
  return [i.split(' ', 1)[0] for i in dates]

### END FUNCTION